# Use postgres/example user/password credentials
version: '3'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: onfly

    ports: 
      - 5432:5432
    networks:
      - onfly

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - onfly

  onfly:
    depends_on:
      - db
    build:
      context: .
    container_name: TesteOnfly
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:8000
    networks:
      - onfly

networks:
  onfly:
    driver: bridge

  